name: Build n Release

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    # Install latest CMake and Ninja.
    - uses: lukka/get-cmake@latest

    # Build dev
    - name: Build DEV
      shell: bash
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug -Bbuild
        cmake --build build --config Debug
        cmake --install build --config Debug

    # Build tagged
    - name: Build Tagged
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Release -Bbuild
        cmake --build build --config Release
        cmake --install build --config Release

    - name: Get Version
      shell: bash
      id: version
      run: |
        echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Release Dev Build
      uses: softprops/action-gh-release@v1
      with:
        name: Dev Build (${{ steps.version.outputs.commit }})
        tag_name: DEV
        fail_on_unmatched_files: true
        prerelease: true
        files: | # NOTE: files have to be overriden each time, otherwise they will pile up infinitely
          usb-facade-win64.zip

    - name: Release Tagged Build
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        files: |
          usb-facade-win64.zip
